### ISSUE TITLE
Program can not run unless everything is done inside the "corason-conda/" folder

### ISSUE THREAD

**Issue by Bedxxe** [miguel-mx/corason-conda#1]
the user must be inside the corason-conda/ folder to be able to use the set of programs that comes with the CORASON repository. I tried to create a directory apart from where I downloaded the CORASON files using absolute paths to call for the functions (_i.e._ gbkIndex.pl and corason.pl). I was unable to do it. The _gbkIndex.pl_ had generated an incomplete output. Once I put my files inside the corason-conda/EXAMPLE2/ folder, I was able to do the analysis.

**Comment by nselem** [comment]
Thanks, Bedxxe, yes this is a preliminary version, and paths should be followed as in this tutorial https://czirion.github.io/comparative-genomics-workshop/
